@ECHO OFF
REM -------------------------------------------------------------------
REM File    : VCInit.Bat
REM -------------------------------------------------------------------

ECHO ERROR: This batch file, VCInit.bat is a placeholder for a batch file that
ECHO        is generated by the tool VCDetect.exe, called from setenv.bat.
ECHO        It will be deleted and replaced when VCDetect.exe is called.