//+--------------------------------------------------------------------------
//
// Microsoft Windows
// Copyright (C) Microsoft Corporation, 1996 - 1999
//
// File:        certbcli.idl
//
// Contents:    IDL imports for certbcli.h
//
//---------------------------------------------------------------------------

#include <SpecStrings.h>
typedef __nullterminated WCHAR *        PWSTR;
typedef __nullterminated WCHAR const *  PCWSTR;
typedef __nullterminated CHAR *         PSTR;
typedef __nullterminated CHAR const *   PCSTR;
#include "certbcli.h"

