//-----------------------------------------------------------------------------
// File:			cmdstrm.idl
//
// Copyright:		Copyright (c) Microsoft Corporation          
//
// Contents: 		OLE DB interface definition
//
// Comments: 		
//
//-----------------------------------------------------------------------------

#include "idlmulti.h"
//

    LOCAL_INTERFACE(0c733abf-2a1c-11ce-ade5-00aa0044773d)


interface ICommandStream : IUnknown {

	[local]
	HRESULT GetCommandStream(
		[out, annotation("__out_opt")] IID * piid,
		[in,out, annotation("__inout_opt")] GUID * pguidDialect,
		[out, iid_is(*piid), annotation("__deref_out")] IUnknown ** ppCommandStream
	);

	[local]
	HRESULT SetCommandStream(
		[in] REFIID riid,
		[in] REFGUID rguidDialect,
		[in, iid_is(riid), annotation("__in_opt")] IUnknown * pCommandStream
	);

}

