// Common definitions used across API
//
// ISSUE: DocID's are currently 32 bit.  If we use them to cross multiple
// catalogs, they might need to be bigger to refer to catalogs as
// well.  (Alternatively 6 bits for catalog (64 catalogs and 64
// million documents).
typedef LONG ITEMID;




