//-----------------------------------------------------------------------------
// File:			asysta.idl
//
// Copyright:		Copyright (c) Microsoft Corporation
//
// Contents: 		OLE DB interface definition
//
// Comments:
//
//-----------------------------------------------------------------------------

#include "idlmulti.h"
//
	REMOTED_INTERFACE(0c733a95-2a1c-11ce-ade5-00aa0044773d)

interface IDBAsynchStatus : IUnknown {

	[local]
	HRESULT Abort(
		[in] HCHAPTER hChapter,
		[in] DBASYNCHOP eOperation
	);

	[call_as(Abort)]
	HRESULT RemoteAbort(
		[in] HCHAPTER hChapter,
		[in] DBASYNCHOP eOperation,
		[out] IErrorInfo ** ppErrorInfoRem
	);

	[local]
	HRESULT GetStatus(
		[in] HCHAPTER hChapter,
		[in] DBASYNCHOP eOperation,
		[out, annotation("__out_opt")] DBCOUNTITEM * pulProgress,
		[out, annotation("__out_opt")] DBCOUNTITEM * pulProgressMax,
		[out, annotation("__out")] DBASYNCHPHASE * peAsynchPhase,
		[out, annotation("__deref_opt_inout_opt")] LPOLESTR * ppwszStatusText
	);

	[call_as(GetStatus)]
	HRESULT RemoteGetStatus(
		[in] HCHAPTER hChapter,
		[in] DBASYNCHOP eOperation,
		[in,out,unique] DBCOUNTITEM * pulProgress,
		[in,out,unique] DBCOUNTITEM * pulProgressMax,
		[in,out,unique] DBASYNCHPHASE * peAsynchPhase,
		[in,out,unique] LPOLESTR * ppwszStatusText,
		[out] IErrorInfo ** ppErrorInfoRem
	);

}

