//-----------------------------------------------------------------------------
// File:			vwchp.idl
//
// Copyright:		Copyright (c) Microsoft Corporation          
//
// Contents: 		OLE DB interface definition
//
// Comments: 		
//
//-----------------------------------------------------------------------------

#include "idlmulti.h"
//
    REMOTED_INTERFACE(0c733a98-2a1c-11ce-ade5-00aa0044773d)

interface IViewChapter : IUnknown {

	[local]
	HRESULT GetSpecification(
		[in, annotation("__in")] REFIID riid,
		[out, iid_is(riid), annotation("__deref_out")] IUnknown ** ppRowset
	);

	[call_as(GetSpecification)]
	HRESULT RemoteGetSpecification(
		[in] REFIID riid,
		[out, iid_is(riid)] IUnknown ** ppRowset,
		[out] IErrorInfo ** ppErrorInfoRem
	);

	[local]
	HRESULT OpenViewChapter(
		[in] HCHAPTER hSource,
		[out, annotation("__out_opt")] HCHAPTER * phViewChapter
	);

	[call_as(OpenViewChapter)]
	HRESULT RemoteOpenViewChapter(
		[in] HCHAPTER hSource,
		[out] HCHAPTER * phViewChapter,
		[out] IErrorInfo ** ppErrorInfoRem
	);

}

