

/* this ALWAYS GENERATED file contains the definitions for the interfaces */


 /* File created by MIDL compiler version 7.00.0499 */
/* Compiler settings for wmscontext.idl:
    Oicf, W1, Zp8, env=Win32 (32b run)
    protocol : dce , ms_ext, c_ext, robust
    error checks: allocation ref bounds_check enum stub_data 
    VC __declspec() decoration level: 
         __declspec(uuid()), __declspec(selectany), __declspec(novtable)
         DECLSPEC_UUID(), MIDL_INTERFACE()
*/
//@@MIDL_FILE_HEADING(  )

#pragma warning( disable: 4049 )  /* more than 64k source lines */


/* verify that the <rpcndr.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 500
#endif

/* verify that the <rpcsal.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCSAL_H_VERSION__
#define __REQUIRED_RPCSAL_H_VERSION__ 100
#endif

#include "rpc.h"
#include "rpcndr.h"

#ifndef __RPCNDR_H_VERSION__
#error this stub requires an updated version of <rpcndr.h>
#endif // __RPCNDR_H_VERSION__

#ifndef COM_NO_WINDOWS_H
#include "windows.h"
#include "ole2.h"
#endif /*COM_NO_WINDOWS_H*/

#ifndef __wmscontext_h__
#define __wmscontext_h__

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

/* Forward Declarations */ 

#ifndef __IWMSContext_FWD_DEFINED__
#define __IWMSContext_FWD_DEFINED__
typedef interface IWMSContext IWMSContext;
#endif 	/* __IWMSContext_FWD_DEFINED__ */


#ifndef __IWMSCommandContext_FWD_DEFINED__
#define __IWMSCommandContext_FWD_DEFINED__
typedef interface IWMSCommandContext IWMSCommandContext;
#endif 	/* __IWMSCommandContext_FWD_DEFINED__ */


/* header files for imported files */
#include "oaidl.h"

#ifdef __cplusplus
extern "C"{
#endif 


/* interface __MIDL_itf_wmscontext_0000_0000 */
/* [local] */ 

//*****************************************************************************
//
// Microsoft Windows Media
// Copyright (C) Microsoft Corporation. All rights reserved.
//
// Automatically generated by Midl from wmscontext.idl
//
// DO NOT EDIT THIS FILE.
//
//*****************************************************************************
#ifndef _WMSContext
#define _WMSContext
typedef unsigned __int64 QWORD;

EXTERN_GUID( IID_IWMSContext, 0x4f1a1421, 0x5cd5, 0x11d2, 0x9f, 0x5, 0x0, 0x60, 0x97, 0xd2, 0xd7, 0xcf );
EXTERN_GUID( IID_IWMSCommandContext, 0x75554931, 0x5f0e, 0x11d2, 0x9f, 0xe, 0x0, 0x60, 0x97, 0xd2, 0xd7, 0xcf );
typedef /* [public] */ 
enum WMS_CONTEXT_OPTIONS
    {	WMS_CONTEXT_SET_PROPERTY_NAME_BY_VALUE	= 0x1,
	WMS_CONTEXT_SET_PROPERTY_STRING_BY_REFERENCE	= 0x2,
	WMS_CONTEXT_GET_PROPERTY_STRING_BY_REFERENCE	= 0x4
    } 	WMS_CONTEXT_OPTIONS;

typedef /* [public] */ 
enum WMS_CONTEXT_HINT_CONSTANTS
    {	WMS_CONTEXT_NO_NAME_HINT	= 0xffffffff
    } 	WMS_CONTEXT_HINT_CONSTANTS;





extern RPC_IF_HANDLE __MIDL_itf_wmscontext_0000_0000_v0_0_c_ifspec;
extern RPC_IF_HANDLE __MIDL_itf_wmscontext_0000_0000_v0_0_s_ifspec;

#ifndef __IWMSContext_INTERFACE_DEFINED__
#define __IWMSContext_INTERFACE_DEFINED__

/* interface IWMSContext */
/* [helpstring][unique][uuid][object] */ 

typedef /* [public] */ 
enum WMS_CONTEXT_TYPE
    {	WMS_UNKNOWN_CONTEXT_TYPE	= 0,
	WMS_SERVER_CONTEXT_TYPE	= ( WMS_UNKNOWN_CONTEXT_TYPE + 1 ) ,
	WMS_USER_CONTEXT_TYPE	= ( WMS_SERVER_CONTEXT_TYPE + 1 ) ,
	WMS_PRESENTATION_CONTEXT_TYPE	= ( WMS_USER_CONTEXT_TYPE + 1 ) ,
	WMS_CONTENT_DESCRIPTION_CONTEXT_TYPE	= ( WMS_PRESENTATION_CONTEXT_TYPE + 1 ) ,
	WMS_COMMAND_REQUEST_CONTEXT_TYPE	= ( WMS_CONTENT_DESCRIPTION_CONTEXT_TYPE + 1 ) ,
	WMS_COMMAND_RESPONSE_CONTEXT_TYPE	= ( WMS_COMMAND_REQUEST_CONTEXT_TYPE + 1 ) ,
	WMS_TRANSPORT_SPEC_CONTEXT_TYPE	= ( WMS_COMMAND_RESPONSE_CONTEXT_TYPE + 1 ) ,
	WMS_PACKETIZER_CONTEXT_TYPE	= ( WMS_TRANSPORT_SPEC_CONTEXT_TYPE + 1 ) ,
	WMS_CACHE_CONTENT_INFORMATION_CONTEXT_TYPE	= ( WMS_PACKETIZER_CONTEXT_TYPE + 1 ) ,
	WMS_ARCHIVE_CONTEXT_TYPE	= ( WMS_CACHE_CONTENT_INFORMATION_CONTEXT_TYPE + 1 ) ,
	WMS_NUM_CONTEXT_TYPE	= ( WMS_ARCHIVE_CONTEXT_TYPE + 1 ) 
    } 	WMS_CONTEXT_TYPE;


EXTERN_C const IID IID_IWMSContext;

#if defined(__cplusplus) && !defined(CINTERFACE)
    
    MIDL_INTERFACE("4F1A1421-5CD5-11d2-9F05-006097D2D7CF")
    IWMSContext : public IUnknown
    {
    public:
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE SetLongValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ long lValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE SetStringValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ __RPC__in LPCWSTR pstrValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE SetIUnknownValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ __RPC__in_opt IUnknown *pValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE SetQwordValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ CURRENCY qwValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE SetDateValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ DATE dateValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE SetArrayValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ __RPC__deref_in_opt SAFEARRAY * psaValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetLongValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__out long *plValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetStringValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__deref_out_opt LPWSTR *pstrValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetIUnknownValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__deref_out_opt IUnknown **pValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetQwordValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__out CURRENCY *pqwValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetDateValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__out DATE *pdateValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetArrayValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__deref_out_opt SAFEARRAY * *ppsaValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE SetValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ VARIANT Value,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__out VARIANT *pValue,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetValueCount( 
            /* [out] */ __RPC__out long *pCount) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetIndexedValue( 
            /* [in] */ long lIndex,
            /* [out] */ __RPC__deref_out_opt LPWSTR *pstrName,
            /* [out] */ __RPC__out long *plNameHint,
            /* [out] */ __RPC__out VARIANT *pValue,
            /* [out] */ __RPC__out long *pdwResultOptions,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE RemoveValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE RemoveAllValues( void) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetContextType( 
            /* [out] */ __RPC__out WMS_CONTEXT_TYPE *pType) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetAndQueryIUnknownValue( 
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ __RPC__in REFIID riid,
            /* [iid_is][out] */ __RPC__deref_out_opt IUnknown **pResult,
            /* [in] */ long lOptions) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE CopyValues( 
            /* [in] */ __RPC__in_opt IWMSContext *pDest,
            /* [in] */ __RPC__deref_in_opt LPCWSTR *pstrName,
            /* [in] */ __RPC__in long *lNameHint,
            /* [in] */ long lNames) = 0;
        
    };
    
#else 	/* C style interface */

    typedef struct IWMSContextVtbl
    {
        BEGIN_INTERFACE
        
        HRESULT ( STDMETHODCALLTYPE *QueryInterface )( 
            IWMSContext * This,
            /* [in] */ __RPC__in REFIID riid,
            /* [iid_is][out] */ 
            __RPC__deref_out  void **ppvObject);
        
        ULONG ( STDMETHODCALLTYPE *AddRef )( 
            IWMSContext * This);
        
        ULONG ( STDMETHODCALLTYPE *Release )( 
            IWMSContext * This);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *SetLongValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ long lValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *SetStringValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ __RPC__in LPCWSTR pstrValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *SetIUnknownValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ __RPC__in_opt IUnknown *pValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *SetQwordValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ CURRENCY qwValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *SetDateValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ DATE dateValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *SetArrayValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ __RPC__deref_in_opt SAFEARRAY * psaValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetLongValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__out long *plValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetStringValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__deref_out_opt LPWSTR *pstrValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetIUnknownValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__deref_out_opt IUnknown **pValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetQwordValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__out CURRENCY *pqwValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetDateValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__out DATE *pdateValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetArrayValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__deref_out_opt SAFEARRAY * *ppsaValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *SetValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ VARIANT Value,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [out] */ __RPC__out VARIANT *pValue,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetValueCount )( 
            IWMSContext * This,
            /* [out] */ __RPC__out long *pCount);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetIndexedValue )( 
            IWMSContext * This,
            /* [in] */ long lIndex,
            /* [out] */ __RPC__deref_out_opt LPWSTR *pstrName,
            /* [out] */ __RPC__out long *plNameHint,
            /* [out] */ __RPC__out VARIANT *pValue,
            /* [out] */ __RPC__out long *pdwResultOptions,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *RemoveValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *RemoveAllValues )( 
            IWMSContext * This);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetContextType )( 
            IWMSContext * This,
            /* [out] */ __RPC__out WMS_CONTEXT_TYPE *pType);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetAndQueryIUnknownValue )( 
            IWMSContext * This,
            /* [in] */ __RPC__in LPCWSTR pstrName,
            /* [in] */ long lNameHint,
            /* [in] */ __RPC__in REFIID riid,
            /* [iid_is][out] */ __RPC__deref_out_opt IUnknown **pResult,
            /* [in] */ long lOptions);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *CopyValues )( 
            IWMSContext * This,
            /* [in] */ __RPC__in_opt IWMSContext *pDest,
            /* [in] */ __RPC__deref_in_opt LPCWSTR *pstrName,
            /* [in] */ __RPC__in long *lNameHint,
            /* [in] */ long lNames);
        
        END_INTERFACE
    } IWMSContextVtbl;

    interface IWMSContext
    {
        CONST_VTBL struct IWMSContextVtbl *lpVtbl;
    };

    

#ifdef COBJMACROS


#define IWMSContext_QueryInterface(This,riid,ppvObject)	\
    ( (This)->lpVtbl -> QueryInterface(This,riid,ppvObject) ) 

#define IWMSContext_AddRef(This)	\
    ( (This)->lpVtbl -> AddRef(This) ) 

#define IWMSContext_Release(This)	\
    ( (This)->lpVtbl -> Release(This) ) 


#define IWMSContext_SetLongValue(This,pstrName,lNameHint,lValue,lOptions)	\
    ( (This)->lpVtbl -> SetLongValue(This,pstrName,lNameHint,lValue,lOptions) ) 

#define IWMSContext_SetStringValue(This,pstrName,lNameHint,pstrValue,lOptions)	\
    ( (This)->lpVtbl -> SetStringValue(This,pstrName,lNameHint,pstrValue,lOptions) ) 

#define IWMSContext_SetIUnknownValue(This,pstrName,lNameHint,pValue,lOptions)	\
    ( (This)->lpVtbl -> SetIUnknownValue(This,pstrName,lNameHint,pValue,lOptions) ) 

#define IWMSContext_SetQwordValue(This,pstrName,lNameHint,qwValue,lOptions)	\
    ( (This)->lpVtbl -> SetQwordValue(This,pstrName,lNameHint,qwValue,lOptions) ) 

#define IWMSContext_SetDateValue(This,pstrName,lNameHint,dateValue,lOptions)	\
    ( (This)->lpVtbl -> SetDateValue(This,pstrName,lNameHint,dateValue,lOptions) ) 

#define IWMSContext_SetArrayValue(This,pstrName,lNameHint,psaValue,lOptions)	\
    ( (This)->lpVtbl -> SetArrayValue(This,pstrName,lNameHint,psaValue,lOptions) ) 

#define IWMSContext_GetLongValue(This,pstrName,lNameHint,plValue,lOptions)	\
    ( (This)->lpVtbl -> GetLongValue(This,pstrName,lNameHint,plValue,lOptions) ) 

#define IWMSContext_GetStringValue(This,pstrName,lNameHint,pstrValue,lOptions)	\
    ( (This)->lpVtbl -> GetStringValue(This,pstrName,lNameHint,pstrValue,lOptions) ) 

#define IWMSContext_GetIUnknownValue(This,pstrName,lNameHint,pValue,lOptions)	\
    ( (This)->lpVtbl -> GetIUnknownValue(This,pstrName,lNameHint,pValue,lOptions) ) 

#define IWMSContext_GetQwordValue(This,pstrName,lNameHint,pqwValue,lOptions)	\
    ( (This)->lpVtbl -> GetQwordValue(This,pstrName,lNameHint,pqwValue,lOptions) ) 

#define IWMSContext_GetDateValue(This,pstrName,lNameHint,pdateValue,lOptions)	\
    ( (This)->lpVtbl -> GetDateValue(This,pstrName,lNameHint,pdateValue,lOptions) ) 

#define IWMSContext_GetArrayValue(This,pstrName,lNameHint,ppsaValue,lOptions)	\
    ( (This)->lpVtbl -> GetArrayValue(This,pstrName,lNameHint,ppsaValue,lOptions) ) 

#define IWMSContext_SetValue(This,pstrName,lNameHint,Value,lOptions)	\
    ( (This)->lpVtbl -> SetValue(This,pstrName,lNameHint,Value,lOptions) ) 

#define IWMSContext_GetValue(This,pstrName,lNameHint,pValue,lOptions)	\
    ( (This)->lpVtbl -> GetValue(This,pstrName,lNameHint,pValue,lOptions) ) 

#define IWMSContext_GetValueCount(This,pCount)	\
    ( (This)->lpVtbl -> GetValueCount(This,pCount) ) 

#define IWMSContext_GetIndexedValue(This,lIndex,pstrName,plNameHint,pValue,pdwResultOptions,lOptions)	\
    ( (This)->lpVtbl -> GetIndexedValue(This,lIndex,pstrName,plNameHint,pValue,pdwResultOptions,lOptions) ) 

#define IWMSContext_RemoveValue(This,pstrName,lNameHint,lOptions)	\
    ( (This)->lpVtbl -> RemoveValue(This,pstrName,lNameHint,lOptions) ) 

#define IWMSContext_RemoveAllValues(This)	\
    ( (This)->lpVtbl -> RemoveAllValues(This) ) 

#define IWMSContext_GetContextType(This,pType)	\
    ( (This)->lpVtbl -> GetContextType(This,pType) ) 

#define IWMSContext_GetAndQueryIUnknownValue(This,pstrName,lNameHint,riid,pResult,lOptions)	\
    ( (This)->lpVtbl -> GetAndQueryIUnknownValue(This,pstrName,lNameHint,riid,pResult,lOptions) ) 

#define IWMSContext_CopyValues(This,pDest,pstrName,lNameHint,lNames)	\
    ( (This)->lpVtbl -> CopyValues(This,pDest,pstrName,lNameHint,lNames) ) 

#endif /* COBJMACROS */


#endif 	/* C style interface */




#endif 	/* __IWMSContext_INTERFACE_DEFINED__ */


#ifndef __IWMSCommandContext_INTERFACE_DEFINED__
#define __IWMSCommandContext_INTERFACE_DEFINED__

/* interface IWMSCommandContext */
/* [helpstring][unique][version][uuid][object] */ 


EXTERN_C const IID IID_IWMSCommandContext;

#if defined(__cplusplus) && !defined(CINTERFACE)
    
    MIDL_INTERFACE("75554931-5F0E-11d2-9F0E-006097D2D7CF")
    IWMSCommandContext : public IUnknown
    {
    public:
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetCommandRequest( 
            /* [out] */ __RPC__deref_out_opt IWMSContext **ppProps) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetCommandResponse( 
            /* [out] */ __RPC__deref_out_opt IWMSContext **ppProps) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE EraseCommandRequest( void) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE EraseCommandResponse( void) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE SetPlaylistGenerationId( 
            /* [in] */ DWORD dwId) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE GetPlaylistGenerationId( 
            /* [out] */ __RPC__out DWORD *pdwId) = 0;
        
    };
    
#else 	/* C style interface */

    typedef struct IWMSCommandContextVtbl
    {
        BEGIN_INTERFACE
        
        HRESULT ( STDMETHODCALLTYPE *QueryInterface )( 
            IWMSCommandContext * This,
            /* [in] */ __RPC__in REFIID riid,
            /* [iid_is][out] */ 
            __RPC__deref_out  void **ppvObject);
        
        ULONG ( STDMETHODCALLTYPE *AddRef )( 
            IWMSCommandContext * This);
        
        ULONG ( STDMETHODCALLTYPE *Release )( 
            IWMSCommandContext * This);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetCommandRequest )( 
            IWMSCommandContext * This,
            /* [out] */ __RPC__deref_out_opt IWMSContext **ppProps);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetCommandResponse )( 
            IWMSCommandContext * This,
            /* [out] */ __RPC__deref_out_opt IWMSContext **ppProps);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *EraseCommandRequest )( 
            IWMSCommandContext * This);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *EraseCommandResponse )( 
            IWMSCommandContext * This);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *SetPlaylistGenerationId )( 
            IWMSCommandContext * This,
            /* [in] */ DWORD dwId);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *GetPlaylistGenerationId )( 
            IWMSCommandContext * This,
            /* [out] */ __RPC__out DWORD *pdwId);
        
        END_INTERFACE
    } IWMSCommandContextVtbl;

    interface IWMSCommandContext
    {
        CONST_VTBL struct IWMSCommandContextVtbl *lpVtbl;
    };

    

#ifdef COBJMACROS


#define IWMSCommandContext_QueryInterface(This,riid,ppvObject)	\
    ( (This)->lpVtbl -> QueryInterface(This,riid,ppvObject) ) 

#define IWMSCommandContext_AddRef(This)	\
    ( (This)->lpVtbl -> AddRef(This) ) 

#define IWMSCommandContext_Release(This)	\
    ( (This)->lpVtbl -> Release(This) ) 


#define IWMSCommandContext_GetCommandRequest(This,ppProps)	\
    ( (This)->lpVtbl -> GetCommandRequest(This,ppProps) ) 

#define IWMSCommandContext_GetCommandResponse(This,ppProps)	\
    ( (This)->lpVtbl -> GetCommandResponse(This,ppProps) ) 

#define IWMSCommandContext_EraseCommandRequest(This)	\
    ( (This)->lpVtbl -> EraseCommandRequest(This) ) 

#define IWMSCommandContext_EraseCommandResponse(This)	\
    ( (This)->lpVtbl -> EraseCommandResponse(This) ) 

#define IWMSCommandContext_SetPlaylistGenerationId(This,dwId)	\
    ( (This)->lpVtbl -> SetPlaylistGenerationId(This,dwId) ) 

#define IWMSCommandContext_GetPlaylistGenerationId(This,pdwId)	\
    ( (This)->lpVtbl -> GetPlaylistGenerationId(This,pdwId) ) 

#endif /* COBJMACROS */


#endif 	/* C style interface */




#endif 	/* __IWMSCommandContext_INTERFACE_DEFINED__ */


/* interface __MIDL_itf_wmscontext_0000_0002 */
/* [local] */ 

#endif


extern RPC_IF_HANDLE __MIDL_itf_wmscontext_0000_0002_v0_0_c_ifspec;
extern RPC_IF_HANDLE __MIDL_itf_wmscontext_0000_0002_v0_0_s_ifspec;

/* Additional Prototypes for ALL interfaces */

unsigned long             __RPC_USER  LPSAFEARRAY_UserSize(     unsigned long *, unsigned long            , LPSAFEARRAY * ); 
unsigned char * __RPC_USER  LPSAFEARRAY_UserMarshal(  unsigned long *, unsigned char *, LPSAFEARRAY * ); 
unsigned char * __RPC_USER  LPSAFEARRAY_UserUnmarshal(unsigned long *, unsigned char *, LPSAFEARRAY * ); 
void                      __RPC_USER  LPSAFEARRAY_UserFree(     unsigned long *, LPSAFEARRAY * ); 

unsigned long             __RPC_USER  VARIANT_UserSize(     unsigned long *, unsigned long            , VARIANT * ); 
unsigned char * __RPC_USER  VARIANT_UserMarshal(  unsigned long *, unsigned char *, VARIANT * ); 
unsigned char * __RPC_USER  VARIANT_UserUnmarshal(unsigned long *, unsigned char *, VARIANT * ); 
void                      __RPC_USER  VARIANT_UserFree(     unsigned long *, VARIANT * ); 

unsigned long             __RPC_USER  LPSAFEARRAY_UserSize64(     unsigned long *, unsigned long            , LPSAFEARRAY * ); 
unsigned char * __RPC_USER  LPSAFEARRAY_UserMarshal64(  unsigned long *, unsigned char *, LPSAFEARRAY * ); 
unsigned char * __RPC_USER  LPSAFEARRAY_UserUnmarshal64(unsigned long *, unsigned char *, LPSAFEARRAY * ); 
void                      __RPC_USER  LPSAFEARRAY_UserFree64(     unsigned long *, LPSAFEARRAY * ); 

unsigned long             __RPC_USER  VARIANT_UserSize64(     unsigned long *, unsigned long            , VARIANT * ); 
unsigned char * __RPC_USER  VARIANT_UserMarshal64(  unsigned long *, unsigned char *, VARIANT * ); 
unsigned char * __RPC_USER  VARIANT_UserUnmarshal64(unsigned long *, unsigned char *, VARIANT * ); 
void                      __RPC_USER  VARIANT_UserFree64(     unsigned long *, VARIANT * ); 

/* end of Additional Prototypes */

#ifdef __cplusplus
}
#endif

#endif



